name: Build and Test

on: [push]

jobs:
  Windows:

    runs-on: windows-latest

    steps:

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Install Packages
      run: |
        choco install cyg-get -y --no-progress
        cyg-get bash patch bison flex make wget perl jq
        nuget install clcache -OutputDirectory "c:\tools" -ExcludeVersion -Version 4.1.0
        cmd.exe /c 'dir c:\tools'
        cmd.exe /c 'dir c:\tools\clcace'

    - uses: actions/cache@v1
      name: Setup cache
      with:
        path: c:\\clcache
        key: ${{ runner.os }}-clcache
        restore-keys: |
          ${{ runner.os }}-clcache

    - uses: actions/checkout@v1

    - name: cbmc submodule checkout
      run: |
        git submodule update --init lib/cbmc

    - name: minisat2-download
      env:
        PATH: c:\\tools\\cygwin\\bin;${PATH}
      run: make -C lib/cbmc/src minisat2-download DOWNLOADER="wget"

    - name: cbmc build
      run: |
        cmd.exe /c 'set PATH=C:\tools\cygwin\bin;C:\tools\clcache;%PATH% && call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 && bash -c "make -j4 -C lib/cbmc/src BUILD_ENV=MSVC CXX=clcache.exe " '

    - name: make
      run: |
        cmd.exe /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 && bash -c "make -j4 -C src BUILD_ENV=MSVC" '
