name: Build and Test

on: [push]

jobs:
  Windows:

    runs-on: windows-latest

    steps:

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Install Packages
      run: |
        choco install cyg-get -y --no-progress
        cyg-get bash patch bison flex make wget perl jq
        nuget install clcache -OutputDirectory "c:\tools" -ExcludeVersion -Version 4.1.0

    - uses: actions/cache@v1
      name: Setup cache
      with:
        path: c:\\clcache
        key: ${{ runner.os }}-clcache
        restore-keys: |
          ${{ runner.os }}-clcache

    - uses: actions/checkout@v1

    - name: cbmc submodule checkout
      run: |
        git submodule update --init lib/cbmc

    - name: minisat2-download
      run: |
        $env:Path = "C:\tools\cygwin\bin;$env:Path"
        make -C lib/cbmc/src minisat2-download DOWNLOADER="wget"

    - name: cbmc build
      run: |
        $env:Path = "C:\tools\cygwin\bin;c:\tools\clcache\clcache-4.1.0;$env:Path"
        $env:CLCACHE_DIR = "C:\clcache"
        $env:CLCACHE_BASEDIR = (Get-Item -Path ".\").FullName
        cmd.exe /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 && bash -c "make -j4 -C lib/cbmc/src BUILD_ENV=MSVC CXX=clcache.exe " '

    - name: make
      run: |
        cmd.exe /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 && bash -c "make -j4 -C src BUILD_ENV=MSVC" '
