name: Build and Test

on: [push]

jobs:
  Linux:

    runs-on: ubuntu-18.04
    
    steps:
    - name: Install Packages
      run: sudo apt-get install ccache flex bison

    - uses: actions/cache@v1
      name: Setup cache
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache
        restore-keys: |
          ${{ runner.os }}-ccache

    - name: ccache stats
      run: ccache -s --max-size=390MB

    - uses: actions/checkout@v1

    - name: cbmc submodule checkout
      run: |
        git submodule update --init lib/cbmc

    - name: minisat2-download
      run: make -C lib/cbmc/src minisat2-download

    - name: cbmc build
      run: |
        make -C lib/cbmc/src -j2 CXX="ccache g++"

    - name: make
      run: make -C src -j2 CXX="ccache g++"

  OSX:

    runs-on: macOS-10.14

    steps:
    - name: Install Packages
      run: |
        brew install libb2
        brew install zstd
        brew install --HEAD ccache

    - uses: actions/cache@v1
      name: Setup cache
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache
        restore-keys: |
          ${{ runner.os }}-ccache

    - name: ccache stats
      run: ccache -s --max-size=390MB

    - uses: actions/checkout@v1

    - name: cbmc submodule checkout
      run: |
        git submodule update --init lib/cbmc

    - name: minisat2-download
      run: make -C lib/cbmc/src minisat2-download

    - name: cbmc build
      run: |
        make -C lib/cbmc/src -j2 CXX="ccache clang++"

    - name: make
      run: make -C src -j2 CXX="ccache clang++"

  Windows:

    runs-on: windows-latest

    steps:
    - name: Install Packages
      run: |
        choco install cyg-get -y --no-progress
        cyg-get bash patch bison flex make wget perl jq
        cmd.exe /c 'set PATH=c:\tools\cygwin\bin;%PATH% && wget https://github.com/frerich/clcache/releases/download/v4.2.0/clcache.4.2.0.nupkg '
        choco install clcache --source=.

    - uses: actions/cache@v1
      name: Setup cache
      with:
        path: c:\\clcache
        key: ${{ runner.os }}-clcache
        restore-keys: |
          ${{ runner.os }}-clcache

    - uses: actions/checkout@v1

    - name: cbmc submodule checkout
      run: |
        git submodule update --init lib/cbmc

    - name: minisat2-download
      env:
        PATH: c:\\tools\\cygwin\\bin;${PATH}
      run: make -C lib/cbmc/src minisat2-download DOWNLOADER="wget"

    - name: cbmc build
      run: |
        cmd.exe /c 'set PATH=C:\tools\cygwin\bin;%PATH% && call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 && bash -c "make -j4 -C lib/cbmc/src BUILD_ENV=MSVC CXX=clcache.exe " '

    - name: make
      run: |
        cmd.exe /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 && bash -c "make -j4 -C src BUILD_ENV=MSVC CXX=clcache.exe" '
